### ISSUE TITLE
Bintray went off into the sunset / Secure Connection Failed

### ISSUE THREAD

**Issue by MaxPeal** [on-prem/tinycore-extensions#1]
its this also never ended up deploying in production?
> I never ended up deploying this to production so it's not currently in use.
> If you need it, please feel free to make a pull request with the changes you want, and i'll be happy to review and accept if it's good.
https://github.com/on-prem/tinycore-cloud-init/issues/1#issuecomment-1056396852

Bintray went off into the sunset,
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

and also the links are dead e.g.

Secure Connection Failed

An error occurred during a connection to dl.bintray.com. PR_END_OF_FILE_ERROR

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.

**Comment by aw** [comment]
Hi @MaxPeal, I'm not sure what's the issue here. This repo is simply a set of **Makefiles** for building tinycore extensions. It has no relation or dependence on Bintray.

Just clone the repo onto a tinycore machine, ensure the required build extensions are loaded (`compiletc, git, coreutils`), and then cd into the extension you want to build and type `make`. It defaults to `11.0-x86_64` but you can change that with `make TC_VERSION=<something>`.

I haven't updated the versions of the extensions here, and you can't get the pre-built binaries anymore, but it's all open source so you're free to copy/modify the code to suit your needs.
